-- KAN-32: generated from source_ddl.py and approved schema.json.
CREATE SCHEMA rmrg;

CREATE FUNCTION rmrg.maintain_audit() RETURNS trigger LANGUAGE plpgsql AS $audit$
BEGIN
    IF to_jsonb(NEW)->TG_ARGV[0] IS DISTINCT FROM to_jsonb(OLD)->TG_ARGV[0] THEN
        RAISE EXCEPTION 'Source primary key is immutable';
    END IF;
    IF NEW.created_at IS DISTINCT FROM OLD.created_at OR NEW.created_by IS DISTINCT FROM OLD.created_by THEN
        RAISE EXCEPTION 'Creation audit is immutable';
    END IF;
    IF TG_TABLE_NAME = 'inventory' THEN
        IF (to_jsonb(NEW)->'product_id') IS DISTINCT FROM (to_jsonb(OLD)->'product_id')
           OR (to_jsonb(NEW)->'store_id') IS DISTINCT FROM (to_jsonb(OLD)->'store_id')
           OR (to_jsonb(NEW)->'warehouse_id') IS DISTINCT FROM (to_jsonb(OLD)->'warehouse_id') THEN
            RAISE EXCEPTION 'Inventory grain is immutable';
        END IF;
    END IF;
    IF (to_jsonb(NEW) - ARRAY['updated_at','row_version','updated_by'])
       IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['updated_at','row_version','updated_by']) THEN
        NEW.updated_at := greatest(clock_timestamp(), OLD.updated_at);
        NEW.row_version := OLD.row_version + 1;
    ELSE
        NEW.updated_at := OLD.updated_at;
        NEW.row_version := OLD.row_version;
        NEW.updated_by := OLD.updated_by;
    END IF;
    RETURN NEW;
END
$audit$;

CREATE TABLE "rmrg"."customers" (
    "customer_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "customer_number" varchar(30) NOT NULL,
    "first_name" varchar(100) NOT NULL,
    "last_name" varchar(100) NOT NULL,
    "email" varchar(254),
    "phone" varchar(25),
    "preferred_language" varchar(10) DEFAULT 'en-CA' NOT NULL,
    "loyalty_tier" varchar(20) DEFAULT 'none' NOT NULL,
    "lifecycle_status" varchar(20) NOT NULL,
    "marketing_opt_in" boolean DEFAULT false NOT NULL,
    "registered_at" timestamp with time zone NOT NULL,
    "anonymized_at" timestamp with time zone,
    "archived_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("customer_number"),
    CONSTRAINT "customers_ck_0" CHECK ((anonymized_at IS NOT NULL) = (lifecycle_status = 'anonymized')),
    CONSTRAINT "customers_ck_1" CHECK (lifecycle_status <> 'anonymized' OR (email IS NULL AND phone IS NULL AND NOT marketing_opt_in)),
    CONSTRAINT "customers_ck_2" CHECK (anonymized_at >= registered_at),
    CONSTRAINT "customers_ck_3" CHECK (archived_at >= registered_at),
    CONSTRAINT "customers_ck_4" CHECK (customer_id > 0),
    CONSTRAINT "customers_ck_5" CHECK (row_version > 0),
    CONSTRAINT "customers_ck_6" CHECK (updated_at >= created_at),
    CONSTRAINT "customers_ck_7" CHECK ("customer_number" IS NULL OR btrim("customer_number") <> ''),
    CONSTRAINT "customers_ck_8" CHECK ("customer_number" = upper(btrim("customer_number")) AND "customer_number" !~ '[^ -~]'),
    CONSTRAINT "customers_ck_9" CHECK ("first_name" IS NULL OR btrim("first_name") <> ''),
    CONSTRAINT "customers_ck_10" CHECK ("last_name" IS NULL OR btrim("last_name") <> ''),
    CONSTRAINT "customers_ck_11" CHECK ("email" IS NULL OR btrim("email") <> ''),
    CONSTRAINT "customers_ck_12" CHECK ("email" = lower(btrim("email"))),
    CONSTRAINT "customers_ck_13" CHECK ("phone" IS NULL OR btrim("phone") <> ''),
    CONSTRAINT "customers_ck_14" CHECK ("phone" ~ '^\+[1-9][0-9]{6,14}$'),
    CONSTRAINT "customers_ck_15" CHECK ("preferred_language" IS NULL OR btrim("preferred_language") <> ''),
    CONSTRAINT "customers_ck_16" CHECK ("preferred_language" IN ('en-CA', 'en-US', 'fr-CA')),
    CONSTRAINT "customers_ck_17" CHECK ("loyalty_tier" IS NULL OR btrim("loyalty_tier") <> ''),
    CONSTRAINT "customers_ck_18" CHECK ("loyalty_tier" IN ('gold', 'none', 'platinum', 'silver')),
    CONSTRAINT "customers_ck_19" CHECK ("lifecycle_status" IS NULL OR btrim("lifecycle_status") <> ''),
    CONSTRAINT "customers_ck_20" CHECK ("lifecycle_status" IN ('active', 'anonymized', 'inactive')),
    CONSTRAINT "customers_ck_21" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "customers_ck_22" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "customers_ix_0" ON "rmrg"."customers" (lower(email)) WHERE email IS NOT NULL;

CREATE INDEX "customers_ix_1" ON "rmrg"."customers" (lifecycle_status, customer_id);

CREATE TRIGGER "customers_audit" BEFORE UPDATE ON rmrg."customers" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('customer_id');

CREATE TABLE "rmrg"."customer_addresses" (
    "customer_address_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "customer_id" bigint NOT NULL,
    "address_label" varchar(50),
    "recipient_name" varchar(200) NOT NULL,
    "address_line1" varchar(200) NOT NULL,
    "address_line2" varchar(200),
    "city" varchar(100) NOT NULL,
    "region" varchar(100),
    "postal_code" varchar(20),
    "country_code" char(2) NOT NULL,
    "phone" varchar(25),
    "is_default_shipping" boolean DEFAULT false NOT NULL,
    "is_default_billing" boolean DEFAULT false NOT NULL,
    "archived_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("customer_address_id", "customer_id"),
    FOREIGN KEY ("customer_id") REFERENCES "rmrg"."customers" ("customer_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "customer_addresses_ck_0" CHECK (archived_at IS NULL OR (NOT is_default_shipping AND NOT is_default_billing)),
    CONSTRAINT "customer_addresses_ck_1" CHECK (archived_at >= created_at),
    CONSTRAINT "customer_addresses_ck_2" CHECK (customer_address_id > 0),
    CONSTRAINT "customer_addresses_ck_3" CHECK (row_version > 0),
    CONSTRAINT "customer_addresses_ck_4" CHECK (updated_at >= created_at),
    CONSTRAINT "customer_addresses_ck_5" CHECK ("address_label" IS NULL OR btrim("address_label") <> ''),
    CONSTRAINT "customer_addresses_ck_6" CHECK ("recipient_name" IS NULL OR btrim("recipient_name") <> ''),
    CONSTRAINT "customer_addresses_ck_7" CHECK ("address_line1" IS NULL OR btrim("address_line1") <> ''),
    CONSTRAINT "customer_addresses_ck_8" CHECK ("address_line2" IS NULL OR btrim("address_line2") <> ''),
    CONSTRAINT "customer_addresses_ck_9" CHECK ("city" IS NULL OR btrim("city") <> ''),
    CONSTRAINT "customer_addresses_ck_10" CHECK ("region" IS NULL OR btrim("region") <> ''),
    CONSTRAINT "customer_addresses_ck_11" CHECK ("postal_code" IS NULL OR btrim("postal_code") <> ''),
    CONSTRAINT "customer_addresses_ck_12" CHECK ("country_code" IS NULL OR btrim("country_code") <> ''),
    CONSTRAINT "customer_addresses_ck_13" CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT "customer_addresses_ck_14" CHECK ("phone" IS NULL OR btrim("phone") <> ''),
    CONSTRAINT "customer_addresses_ck_15" CHECK ("phone" ~ '^\+[1-9][0-9]{6,14}$'),
    CONSTRAINT "customer_addresses_ck_16" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "customer_addresses_ck_17" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "customer_addresses_ix_0" ON "rmrg"."customer_addresses" (customer_id, archived_at);

CREATE UNIQUE INDEX "customer_addresses_ix_1" ON "rmrg"."customer_addresses" (customer_id) WHERE is_default_shipping AND archived_at IS NULL;

CREATE UNIQUE INDEX "customer_addresses_ix_2" ON "rmrg"."customer_addresses" (customer_id) WHERE is_default_billing AND archived_at IS NULL;

CREATE TRIGGER "customer_addresses_audit" BEFORE UPDATE ON rmrg."customer_addresses" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('customer_address_id');

CREATE TABLE "rmrg"."product_categories" (
    "category_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "category_code" varchar(30) NOT NULL,
    "parent_category_id" bigint,
    "category_name" varchar(150) NOT NULL,
    "description" varchar(1000),
    "sort_order" integer DEFAULT 0 NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "archived_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("category_code"),
    FOREIGN KEY ("parent_category_id") REFERENCES "rmrg"."product_categories" ("category_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "product_categories_ck_0" CHECK (parent_category_id <> category_id),
    CONSTRAINT "product_categories_ck_1" CHECK (sort_order >= 0),
    CONSTRAINT "product_categories_ck_2" CHECK (archived_at IS NULL OR NOT is_active),
    CONSTRAINT "product_categories_ck_3" CHECK (archived_at >= created_at),
    CONSTRAINT "product_categories_ck_4" CHECK (category_id > 0),
    CONSTRAINT "product_categories_ck_5" CHECK (row_version > 0),
    CONSTRAINT "product_categories_ck_6" CHECK (updated_at >= created_at),
    CONSTRAINT "product_categories_ck_7" CHECK ("category_code" IS NULL OR btrim("category_code") <> ''),
    CONSTRAINT "product_categories_ck_8" CHECK ("category_code" = upper(btrim("category_code")) AND "category_code" !~ '[^ -~]'),
    CONSTRAINT "product_categories_ck_9" CHECK ("category_name" IS NULL OR btrim("category_name") <> ''),
    CONSTRAINT "product_categories_ck_10" CHECK ("description" IS NULL OR btrim("description") <> ''),
    CONSTRAINT "product_categories_ck_11" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "product_categories_ck_12" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "product_categories_ix_0" ON "rmrg"."product_categories" (parent_category_id, sort_order, category_id);

CREATE TRIGGER "product_categories_audit" BEFORE UPDATE ON rmrg."product_categories" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('category_id');

CREATE TABLE "rmrg"."products" (
    "product_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "sku" varchar(50) NOT NULL,
    "category_id" bigint NOT NULL,
    "product_name" varchar(200) NOT NULL,
    "description" varchar(2000),
    "brand" varchar(100),
    "style_code" varchar(50),
    "size_label" varchar(30),
    "color_name" varchar(50),
    "barcode" varchar(50),
    "unit_of_measure" varchar(10) NOT NULL,
    "list_price" numeric(18,2) NOT NULL,
    "standard_cost" numeric(18,2),
    "currency_code" char(3) NOT NULL,
    "weight_kg" numeric(10,3),
    "lifecycle_status" varchar(20) NOT NULL,
    "launched_at" timestamp with time zone,
    "discontinued_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("sku"),
    FOREIGN KEY ("category_id") REFERENCES "rmrg"."product_categories" ("category_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "products_ck_0" CHECK (weight_kg > 0),
    CONSTRAINT "products_ck_1" CHECK (lifecycle_status <> 'active' OR launched_at IS NOT NULL),
    CONSTRAINT "products_ck_2" CHECK ((discontinued_at IS NOT NULL) = (lifecycle_status = 'discontinued')),
    CONSTRAINT "products_ck_3" CHECK (discontinued_at >= launched_at),
    CONSTRAINT "products_ck_4" CHECK (product_id > 0),
    CONSTRAINT "products_ck_5" CHECK (row_version > 0),
    CONSTRAINT "products_ck_6" CHECK (updated_at >= created_at),
    CONSTRAINT "products_ck_7" CHECK ("sku" IS NULL OR btrim("sku") <> ''),
    CONSTRAINT "products_ck_8" CHECK ("sku" = upper(btrim("sku")) AND "sku" !~ '[^ -~]'),
    CONSTRAINT "products_ck_9" CHECK ("product_name" IS NULL OR btrim("product_name") <> ''),
    CONSTRAINT "products_ck_10" CHECK ("description" IS NULL OR btrim("description") <> ''),
    CONSTRAINT "products_ck_11" CHECK ("brand" IS NULL OR btrim("brand") <> ''),
    CONSTRAINT "products_ck_12" CHECK ("style_code" IS NULL OR btrim("style_code") <> ''),
    CONSTRAINT "products_ck_13" CHECK ("style_code" = upper(btrim("style_code")) AND "style_code" !~ '[^ -~]'),
    CONSTRAINT "products_ck_14" CHECK ("size_label" IS NULL OR btrim("size_label") <> ''),
    CONSTRAINT "products_ck_15" CHECK ("color_name" IS NULL OR btrim("color_name") <> ''),
    CONSTRAINT "products_ck_16" CHECK ("barcode" IS NULL OR btrim("barcode") <> ''),
    CONSTRAINT "products_ck_17" CHECK ("unit_of_measure" IS NULL OR btrim("unit_of_measure") <> ''),
    CONSTRAINT "products_ck_18" CHECK ("unit_of_measure" IN ('each')),
    CONSTRAINT "products_ck_19" CHECK ("list_price" >= 0),
    CONSTRAINT "products_ck_20" CHECK ("standard_cost" >= 0),
    CONSTRAINT "products_ck_21" CHECK ("currency_code" IS NULL OR btrim("currency_code") <> ''),
    CONSTRAINT "products_ck_22" CHECK (currency_code IN ('CAD','USD')),
    CONSTRAINT "products_ck_23" CHECK ("lifecycle_status" IS NULL OR btrim("lifecycle_status") <> ''),
    CONSTRAINT "products_ck_24" CHECK ("lifecycle_status" IN ('active', 'discontinued', 'draft')),
    CONSTRAINT "products_ck_25" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "products_ck_26" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "products_ix_0" ON "rmrg"."products" (category_id, lifecycle_status);

CREATE INDEX "products_ix_1" ON "rmrg"."products" (style_code) WHERE style_code IS NOT NULL;

CREATE UNIQUE INDEX "products_ix_2" ON "rmrg"."products" (barcode) WHERE barcode IS NOT NULL;

CREATE TRIGGER "products_audit" BEFORE UPDATE ON rmrg."products" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('product_id');

CREATE TABLE "rmrg"."stores" (
    "store_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "store_code" varchar(30) NOT NULL,
    "store_name" varchar(150) NOT NULL,
    "store_type" varchar(20) NOT NULL,
    "address_line1" varchar(200) NOT NULL,
    "address_line2" varchar(200),
    "city" varchar(100) NOT NULL,
    "region" varchar(100),
    "postal_code" varchar(20),
    "country_code" char(2) NOT NULL,
    "timezone_name" varchar(64) NOT NULL,
    "phone" varchar(25),
    "supports_pickup" boolean NOT NULL,
    "supports_ship_from_store" boolean NOT NULL,
    "lifecycle_status" varchar(20) NOT NULL,
    "opened_on" date,
    "closed_on" date,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("store_code"),
    CONSTRAINT "stores_ck_0" CHECK (lifecycle_status = 'planned' OR opened_on IS NOT NULL),
    CONSTRAINT "stores_ck_1" CHECK ((closed_on IS NOT NULL) = (lifecycle_status = 'closed')),
    CONSTRAINT "stores_ck_2" CHECK (closed_on >= opened_on),
    CONSTRAINT "stores_ck_3" CHECK (store_id > 0),
    CONSTRAINT "stores_ck_4" CHECK (row_version > 0),
    CONSTRAINT "stores_ck_5" CHECK (updated_at >= created_at),
    CONSTRAINT "stores_ck_6" CHECK ("store_code" IS NULL OR btrim("store_code") <> ''),
    CONSTRAINT "stores_ck_7" CHECK ("store_code" = upper(btrim("store_code")) AND "store_code" !~ '[^ -~]'),
    CONSTRAINT "stores_ck_8" CHECK ("store_name" IS NULL OR btrim("store_name") <> ''),
    CONSTRAINT "stores_ck_9" CHECK ("store_type" IS NULL OR btrim("store_type") <> ''),
    CONSTRAINT "stores_ck_10" CHECK ("store_type" IN ('full_service', 'outlet', 'popup')),
    CONSTRAINT "stores_ck_11" CHECK ("address_line1" IS NULL OR btrim("address_line1") <> ''),
    CONSTRAINT "stores_ck_12" CHECK ("address_line2" IS NULL OR btrim("address_line2") <> ''),
    CONSTRAINT "stores_ck_13" CHECK ("city" IS NULL OR btrim("city") <> ''),
    CONSTRAINT "stores_ck_14" CHECK ("region" IS NULL OR btrim("region") <> ''),
    CONSTRAINT "stores_ck_15" CHECK ("postal_code" IS NULL OR btrim("postal_code") <> ''),
    CONSTRAINT "stores_ck_16" CHECK ("country_code" IS NULL OR btrim("country_code") <> ''),
    CONSTRAINT "stores_ck_17" CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT "stores_ck_18" CHECK ("timezone_name" IS NULL OR btrim("timezone_name") <> ''),
    CONSTRAINT "stores_ck_19" CHECK ("phone" IS NULL OR btrim("phone") <> ''),
    CONSTRAINT "stores_ck_20" CHECK ("phone" ~ '^\+[1-9][0-9]{6,14}$'),
    CONSTRAINT "stores_ck_21" CHECK ("lifecycle_status" IS NULL OR btrim("lifecycle_status") <> ''),
    CONSTRAINT "stores_ck_22" CHECK ("lifecycle_status" IN ('closed', 'open', 'planned', 'temporarily_closed')),
    CONSTRAINT "stores_ck_23" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "stores_ck_24" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "stores_ix_0" ON "rmrg"."stores" (lifecycle_status, country_code, region);

CREATE TRIGGER "stores_audit" BEFORE UPDATE ON rmrg."stores" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('store_id');

CREATE TABLE "rmrg"."warehouses" (
    "warehouse_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "warehouse_code" varchar(30) NOT NULL,
    "warehouse_name" varchar(150) NOT NULL,
    "warehouse_type" varchar(20) NOT NULL,
    "address_line1" varchar(200) NOT NULL,
    "address_line2" varchar(200),
    "city" varchar(100) NOT NULL,
    "region" varchar(100),
    "postal_code" varchar(20),
    "country_code" char(2) NOT NULL,
    "timezone_name" varchar(64) NOT NULL,
    "phone" varchar(25),
    "accepts_returns" boolean NOT NULL,
    "lifecycle_status" varchar(20) NOT NULL,
    "opened_on" date,
    "closed_on" date,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("warehouse_code"),
    CONSTRAINT "warehouses_ck_0" CHECK (lifecycle_status = 'planned' OR opened_on IS NOT NULL),
    CONSTRAINT "warehouses_ck_1" CHECK ((closed_on IS NOT NULL) = (lifecycle_status = 'closed')),
    CONSTRAINT "warehouses_ck_2" CHECK (closed_on >= opened_on),
    CONSTRAINT "warehouses_ck_3" CHECK (warehouse_id > 0),
    CONSTRAINT "warehouses_ck_4" CHECK (row_version > 0),
    CONSTRAINT "warehouses_ck_5" CHECK (updated_at >= created_at),
    CONSTRAINT "warehouses_ck_6" CHECK ("warehouse_code" IS NULL OR btrim("warehouse_code") <> ''),
    CONSTRAINT "warehouses_ck_7" CHECK ("warehouse_code" = upper(btrim("warehouse_code")) AND "warehouse_code" !~ '[^ -~]'),
    CONSTRAINT "warehouses_ck_8" CHECK ("warehouse_name" IS NULL OR btrim("warehouse_name") <> ''),
    CONSTRAINT "warehouses_ck_9" CHECK ("warehouse_type" IS NULL OR btrim("warehouse_type") <> ''),
    CONSTRAINT "warehouses_ck_10" CHECK ("warehouse_type" IN ('distribution', 'fulfillment', 'returns')),
    CONSTRAINT "warehouses_ck_11" CHECK ("address_line1" IS NULL OR btrim("address_line1") <> ''),
    CONSTRAINT "warehouses_ck_12" CHECK ("address_line2" IS NULL OR btrim("address_line2") <> ''),
    CONSTRAINT "warehouses_ck_13" CHECK ("city" IS NULL OR btrim("city") <> ''),
    CONSTRAINT "warehouses_ck_14" CHECK ("region" IS NULL OR btrim("region") <> ''),
    CONSTRAINT "warehouses_ck_15" CHECK ("postal_code" IS NULL OR btrim("postal_code") <> ''),
    CONSTRAINT "warehouses_ck_16" CHECK ("country_code" IS NULL OR btrim("country_code") <> ''),
    CONSTRAINT "warehouses_ck_17" CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT "warehouses_ck_18" CHECK ("timezone_name" IS NULL OR btrim("timezone_name") <> ''),
    CONSTRAINT "warehouses_ck_19" CHECK ("phone" IS NULL OR btrim("phone") <> ''),
    CONSTRAINT "warehouses_ck_20" CHECK ("phone" ~ '^\+[1-9][0-9]{6,14}$'),
    CONSTRAINT "warehouses_ck_21" CHECK ("lifecycle_status" IS NULL OR btrim("lifecycle_status") <> ''),
    CONSTRAINT "warehouses_ck_22" CHECK ("lifecycle_status" IN ('active', 'closed', 'planned', 'temporarily_closed')),
    CONSTRAINT "warehouses_ck_23" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "warehouses_ck_24" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "warehouses_ix_0" ON "rmrg"."warehouses" (lifecycle_status, warehouse_type);

CREATE TRIGGER "warehouses_audit" BEFORE UPDATE ON rmrg."warehouses" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('warehouse_id');

CREATE TABLE "rmrg"."inventory" (
    "inventory_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "product_id" bigint NOT NULL,
    "store_id" bigint,
    "warehouse_id" bigint,
    "quantity_on_hand" integer NOT NULL,
    "quantity_reserved" integer NOT NULL,
    "quantity_unavailable" integer NOT NULL,
    "reorder_point" integer NOT NULL,
    "target_stock_level" integer NOT NULL,
    "last_counted_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    FOREIGN KEY ("product_id") REFERENCES "rmrg"."products" ("product_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("store_id") REFERENCES "rmrg"."stores" ("store_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("warehouse_id") REFERENCES "rmrg"."warehouses" ("warehouse_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "inventory_ck_0" CHECK ((store_id IS NULL) <> (warehouse_id IS NULL)),
    CONSTRAINT "inventory_ck_1" CHECK (quantity_on_hand >= 0),
    CONSTRAINT "inventory_ck_2" CHECK (quantity_reserved >= 0),
    CONSTRAINT "inventory_ck_3" CHECK (quantity_unavailable >= 0),
    CONSTRAINT "inventory_ck_4" CHECK (reorder_point >= 0),
    CONSTRAINT "inventory_ck_5" CHECK (target_stock_level >= reorder_point),
    CONSTRAINT "inventory_ck_6" CHECK (quantity_reserved::bigint + quantity_unavailable::bigint <= quantity_on_hand),
    CONSTRAINT "inventory_ck_7" CHECK (inventory_id > 0),
    CONSTRAINT "inventory_ck_8" CHECK (row_version > 0),
    CONSTRAINT "inventory_ck_9" CHECK (updated_at >= created_at),
    CONSTRAINT "inventory_ck_10" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "inventory_ck_11" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "inventory_ix_0" ON "rmrg"."inventory" (store_id, product_id) WHERE store_id IS NOT NULL;

CREATE INDEX "inventory_ix_1" ON "rmrg"."inventory" (warehouse_id, product_id) WHERE warehouse_id IS NOT NULL;

CREATE UNIQUE INDEX "inventory_ix_2" ON "rmrg"."inventory" (product_id, store_id) WHERE store_id IS NOT NULL;

CREATE UNIQUE INDEX "inventory_ix_3" ON "rmrg"."inventory" (product_id, warehouse_id) WHERE warehouse_id IS NOT NULL;

CREATE TRIGGER "inventory_audit" BEFORE UPDATE ON rmrg."inventory" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('inventory_id');

CREATE TABLE "rmrg"."orders" (
    "order_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "order_number" varchar(40) NOT NULL,
    "order_request_key" varchar(100) NOT NULL,
    "customer_id" bigint,
    "channel" varchar(20) NOT NULL,
    "origin_store_id" bigint,
    "fulfillment_preference" varchar(20) NOT NULL,
    "order_status" varchar(25) DEFAULT 'draft' NOT NULL,
    "currency_code" char(3) NOT NULL,
    "contact_email" varchar(254),
    "contact_phone" varchar(25),
    "merchandise_subtotal" numeric(18,2) NOT NULL,
    "discount_total" numeric(18,2) NOT NULL,
    "merchandise_tax_total" numeric(18,2) NOT NULL,
    "shipping_amount" numeric(18,2) NOT NULL,
    "shipping_tax_amount" numeric(18,2) NOT NULL,
    "order_total" numeric(18,2) NOT NULL,
    "placed_at" timestamp with time zone,
    "cancelled_at" timestamp with time zone,
    "closed_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("order_number"),
    UNIQUE ("order_request_key"),
    UNIQUE ("order_id", "customer_id"),
    FOREIGN KEY ("customer_id") REFERENCES "rmrg"."customers" ("customer_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("origin_store_id") REFERENCES "rmrg"."stores" ("store_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "orders_ck_0" CHECK ((origin_store_id IS NOT NULL) = (channel = 'store')),
    CONSTRAINT "orders_ck_1" CHECK (discount_total <= merchandise_subtotal),
    CONSTRAINT "orders_ck_2" CHECK (order_total = merchandise_subtotal - discount_total + merchandise_tax_total + shipping_amount + shipping_tax_amount),
    CONSTRAINT "orders_ck_3" CHECK ((placed_at IS NULL) = (order_status = 'draft')),
    CONSTRAINT "orders_ck_4" CHECK ((cancelled_at IS NOT NULL) = (order_status = 'cancelled')),
    CONSTRAINT "orders_ck_5" CHECK ((closed_at IS NOT NULL) = (order_status = 'closed')),
    CONSTRAINT "orders_ck_6" CHECK (cancelled_at >= placed_at),
    CONSTRAINT "orders_ck_7" CHECK (closed_at >= placed_at),
    CONSTRAINT "orders_ck_8" CHECK (order_id > 0),
    CONSTRAINT "orders_ck_9" CHECK (row_version > 0),
    CONSTRAINT "orders_ck_10" CHECK (updated_at >= created_at),
    CONSTRAINT "orders_ck_11" CHECK ("order_number" IS NULL OR btrim("order_number") <> ''),
    CONSTRAINT "orders_ck_12" CHECK ("order_number" = upper(btrim("order_number")) AND "order_number" !~ '[^ -~]'),
    CONSTRAINT "orders_ck_13" CHECK ("order_request_key" IS NULL OR btrim("order_request_key") <> ''),
    CONSTRAINT "orders_ck_14" CHECK ("channel" IS NULL OR btrim("channel") <> ''),
    CONSTRAINT "orders_ck_15" CHECK ("channel" IN ('call_center', 'mobile', 'store', 'web')),
    CONSTRAINT "orders_ck_16" CHECK ("fulfillment_preference" IS NULL OR btrim("fulfillment_preference") <> ''),
    CONSTRAINT "orders_ck_17" CHECK ("fulfillment_preference" IN ('carryout', 'mixed', 'pickup', 'ship')),
    CONSTRAINT "orders_ck_18" CHECK ("order_status" IS NULL OR btrim("order_status") <> ''),
    CONSTRAINT "orders_ck_19" CHECK ("order_status" IN ('cancelled', 'closed', 'draft', 'fulfilled', 'partially_fulfilled', 'placed', 'processing')),
    CONSTRAINT "orders_ck_20" CHECK ("currency_code" IS NULL OR btrim("currency_code") <> ''),
    CONSTRAINT "orders_ck_21" CHECK (currency_code IN ('CAD','USD')),
    CONSTRAINT "orders_ck_22" CHECK ("contact_email" IS NULL OR btrim("contact_email") <> ''),
    CONSTRAINT "orders_ck_23" CHECK ("contact_email" = lower(btrim("contact_email"))),
    CONSTRAINT "orders_ck_24" CHECK ("contact_phone" IS NULL OR btrim("contact_phone") <> ''),
    CONSTRAINT "orders_ck_25" CHECK ("contact_phone" ~ '^\+[1-9][0-9]{6,14}$'),
    CONSTRAINT "orders_ck_26" CHECK ("merchandise_subtotal" >= 0),
    CONSTRAINT "orders_ck_27" CHECK ("discount_total" >= 0),
    CONSTRAINT "orders_ck_28" CHECK ("merchandise_tax_total" >= 0),
    CONSTRAINT "orders_ck_29" CHECK ("shipping_amount" >= 0),
    CONSTRAINT "orders_ck_30" CHECK ("shipping_tax_amount" >= 0),
    CONSTRAINT "orders_ck_31" CHECK ("order_total" >= 0),
    CONSTRAINT "orders_ck_32" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "orders_ck_33" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "orders_ix_0" ON "rmrg"."orders" (customer_id, placed_at, order_id);

CREATE INDEX "orders_ix_1" ON "rmrg"."orders" (origin_store_id, placed_at);

CREATE INDEX "orders_ix_2" ON "rmrg"."orders" (order_status, placed_at);

CREATE INDEX "orders_ix_3" ON "rmrg"."orders" (placed_at, order_id);

CREATE TRIGGER "orders_audit" BEFORE UPDATE ON rmrg."orders" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('order_id');

CREATE TABLE "rmrg"."order_addresses" (
    "order_address_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "order_id" bigint NOT NULL,
    "address_role" varchar(10) NOT NULL,
    "source_customer_id" bigint,
    "source_customer_address_id" bigint,
    "recipient_name" varchar(200) NOT NULL,
    "address_line1" varchar(200) NOT NULL,
    "address_line2" varchar(200),
    "city" varchar(100) NOT NULL,
    "region" varchar(100),
    "postal_code" varchar(20),
    "country_code" char(2) NOT NULL,
    "phone" varchar(25),
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("order_id", "address_role"),
    UNIQUE ("order_address_id", "order_id", "address_role"),
    FOREIGN KEY ("order_id") REFERENCES "rmrg"."orders" ("order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("order_id", "source_customer_id") REFERENCES "rmrg"."orders" ("order_id", "customer_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("source_customer_address_id", "source_customer_id") REFERENCES "rmrg"."customer_addresses" ("customer_address_id", "customer_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "order_addresses_ck_0" CHECK ((source_customer_id IS NULL) = (source_customer_address_id IS NULL)),
    CONSTRAINT "order_addresses_ck_1" CHECK (order_address_id > 0),
    CONSTRAINT "order_addresses_ck_2" CHECK (row_version > 0),
    CONSTRAINT "order_addresses_ck_3" CHECK (updated_at >= created_at),
    CONSTRAINT "order_addresses_ck_4" CHECK ("address_role" IS NULL OR btrim("address_role") <> ''),
    CONSTRAINT "order_addresses_ck_5" CHECK ("address_role" IN ('billing', 'shipping')),
    CONSTRAINT "order_addresses_ck_6" CHECK ("recipient_name" IS NULL OR btrim("recipient_name") <> ''),
    CONSTRAINT "order_addresses_ck_7" CHECK ("address_line1" IS NULL OR btrim("address_line1") <> ''),
    CONSTRAINT "order_addresses_ck_8" CHECK ("address_line2" IS NULL OR btrim("address_line2") <> ''),
    CONSTRAINT "order_addresses_ck_9" CHECK ("city" IS NULL OR btrim("city") <> ''),
    CONSTRAINT "order_addresses_ck_10" CHECK ("region" IS NULL OR btrim("region") <> ''),
    CONSTRAINT "order_addresses_ck_11" CHECK ("postal_code" IS NULL OR btrim("postal_code") <> ''),
    CONSTRAINT "order_addresses_ck_12" CHECK ("country_code" IS NULL OR btrim("country_code") <> ''),
    CONSTRAINT "order_addresses_ck_13" CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT "order_addresses_ck_14" CHECK ("phone" IS NULL OR btrim("phone") <> ''),
    CONSTRAINT "order_addresses_ck_15" CHECK ("phone" ~ '^\+[1-9][0-9]{6,14}$'),
    CONSTRAINT "order_addresses_ck_16" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "order_addresses_ck_17" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "order_addresses_ix_0" ON "rmrg"."order_addresses" (source_customer_address_id, source_customer_id);

CREATE INDEX "order_addresses_ix_1" ON "rmrg"."order_addresses" (order_id, source_customer_id);

CREATE TRIGGER "order_addresses_audit" BEFORE UPDATE ON rmrg."order_addresses" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('order_address_id');

CREATE TABLE "rmrg"."order_items" (
    "order_item_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "order_id" bigint NOT NULL,
    "line_number" integer NOT NULL,
    "product_id" bigint NOT NULL,
    "sku_snapshot" varchar(50) NOT NULL,
    "product_name_snapshot" varchar(200) NOT NULL,
    "quantity_ordered" integer NOT NULL,
    "quantity_cancelled" integer DEFAULT 0 NOT NULL,
    "unit_price" numeric(18,2) NOT NULL,
    "unit_cost_snapshot" numeric(18,2),
    "gross_amount" numeric(18,2) NOT NULL,
    "discount_amount" numeric(18,2) NOT NULL,
    "tax_rate_percent" numeric(5,2) NOT NULL,
    "tax_amount" numeric(18,2) NOT NULL,
    "line_total" numeric(18,2) NOT NULL,
    "line_status" varchar(25) DEFAULT 'open' NOT NULL,
    "requested_fulfillment" varchar(20) NOT NULL,
    "requested_pickup_store_id" bigint,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("order_id", "line_number"),
    UNIQUE ("order_item_id", "order_id"),
    FOREIGN KEY ("order_id") REFERENCES "rmrg"."orders" ("order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("product_id") REFERENCES "rmrg"."products" ("product_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("requested_pickup_store_id") REFERENCES "rmrg"."stores" ("store_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "order_items_ck_0" CHECK (line_number > 0),
    CONSTRAINT "order_items_ck_1" CHECK (quantity_ordered > 0),
    CONSTRAINT "order_items_ck_2" CHECK (quantity_cancelled BETWEEN 0 AND quantity_ordered),
    CONSTRAINT "order_items_ck_3" CHECK (gross_amount = quantity_ordered::numeric * unit_price),
    CONSTRAINT "order_items_ck_4" CHECK (discount_amount <= gross_amount),
    CONSTRAINT "order_items_ck_5" CHECK (tax_rate_percent BETWEEN 0 AND 100),
    CONSTRAINT "order_items_ck_6" CHECK (tax_amount = round((gross_amount - discount_amount) * tax_rate_percent / 100, 2)),
    CONSTRAINT "order_items_ck_7" CHECK (line_total = gross_amount - discount_amount + tax_amount),
    CONSTRAINT "order_items_ck_8" CHECK ((quantity_cancelled = quantity_ordered) = (line_status = 'cancelled')),
    CONSTRAINT "order_items_ck_9" CHECK ((requested_pickup_store_id IS NOT NULL) = (requested_fulfillment = 'pickup')),
    CONSTRAINT "order_items_ck_10" CHECK (order_item_id > 0),
    CONSTRAINT "order_items_ck_11" CHECK (row_version > 0),
    CONSTRAINT "order_items_ck_12" CHECK (updated_at >= created_at),
    CONSTRAINT "order_items_ck_13" CHECK ("sku_snapshot" IS NULL OR btrim("sku_snapshot") <> ''),
    CONSTRAINT "order_items_ck_14" CHECK ("sku_snapshot" = upper(btrim("sku_snapshot")) AND "sku_snapshot" !~ '[^ -~]'),
    CONSTRAINT "order_items_ck_15" CHECK ("product_name_snapshot" IS NULL OR btrim("product_name_snapshot") <> ''),
    CONSTRAINT "order_items_ck_16" CHECK ("unit_price" >= 0),
    CONSTRAINT "order_items_ck_17" CHECK ("unit_cost_snapshot" >= 0),
    CONSTRAINT "order_items_ck_18" CHECK ("gross_amount" >= 0),
    CONSTRAINT "order_items_ck_19" CHECK ("discount_amount" >= 0),
    CONSTRAINT "order_items_ck_20" CHECK ("tax_rate_percent" >= 0),
    CONSTRAINT "order_items_ck_21" CHECK ("tax_amount" >= 0),
    CONSTRAINT "order_items_ck_22" CHECK ("line_total" >= 0),
    CONSTRAINT "order_items_ck_23" CHECK ("line_status" IS NULL OR btrim("line_status") <> ''),
    CONSTRAINT "order_items_ck_24" CHECK ("line_status" IN ('cancelled', 'closed', 'fulfilled', 'open', 'partially_fulfilled')),
    CONSTRAINT "order_items_ck_25" CHECK ("requested_fulfillment" IS NULL OR btrim("requested_fulfillment") <> ''),
    CONSTRAINT "order_items_ck_26" CHECK ("requested_fulfillment" IN ('carryout', 'pickup', 'ship')),
    CONSTRAINT "order_items_ck_27" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "order_items_ck_28" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "order_items_ix_0" ON "rmrg"."order_items" (product_id, order_id);

CREATE INDEX "order_items_ix_1" ON "rmrg"."order_items" (requested_pickup_store_id) WHERE requested_pickup_store_id IS NOT NULL;

CREATE TRIGGER "order_items_audit" BEFORE UPDATE ON rmrg."order_items" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('order_item_id');

CREATE TABLE "rmrg"."shipments" (
    "shipment_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "shipment_number" varchar(40) NOT NULL,
    "order_id" bigint NOT NULL,
    "fulfillment_type" varchar(15) NOT NULL,
    "origin_store_id" bigint,
    "origin_warehouse_id" bigint,
    "shipping_address_id" bigint,
    "shipping_address_role" varchar(10),
    "carrier" varchar(50),
    "tracking_number" varchar(100),
    "shipment_status" varchar(20) DEFAULT 'planned' NOT NULL,
    "planned_at" timestamp with time zone NOT NULL,
    "ready_at" timestamp with time zone,
    "handed_over_at" timestamp with time zone,
    "delivered_at" timestamp with time zone,
    "cancelled_at" timestamp with time zone,
    "expected_delivery_on" date,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("shipment_number"),
    UNIQUE ("shipment_id", "order_id"),
    FOREIGN KEY ("order_id") REFERENCES "rmrg"."orders" ("order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("origin_store_id") REFERENCES "rmrg"."stores" ("store_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("origin_warehouse_id") REFERENCES "rmrg"."warehouses" ("warehouse_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("shipping_address_id", "order_id", "shipping_address_role") REFERENCES "rmrg"."order_addresses" ("order_address_id", "order_id", "address_role") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "shipments_ck_0" CHECK ((origin_store_id IS NULL) <> (origin_warehouse_id IS NULL)),
    CONSTRAINT "shipments_ck_1" CHECK (fulfillment_type = 'ship' OR origin_store_id IS NOT NULL),
    CONSTRAINT "shipments_ck_2" CHECK ((shipping_address_id IS NOT NULL) = (fulfillment_type = 'ship')),
    CONSTRAINT "shipments_ck_3" CHECK ((shipping_address_role IS NOT NULL) = (fulfillment_type = 'ship')),
    CONSTRAINT "shipments_ck_4" CHECK ((carrier IS NULL) = (tracking_number IS NULL)),
    CONSTRAINT "shipments_ck_5" CHECK (fulfillment_type = 'ship' OR carrier IS NULL),
    CONSTRAINT "shipments_ck_6" CHECK (fulfillment_type <> 'ship' OR shipment_status NOT IN ('handed_over','delivered') OR carrier IS NOT NULL),
    CONSTRAINT "shipments_ck_7" CHECK (shipment_status NOT IN ('ready','handed_over','delivered') OR ready_at IS NOT NULL),
    CONSTRAINT "shipments_ck_8" CHECK (shipment_status NOT IN ('handed_over','delivered') OR handed_over_at IS NOT NULL),
    CONSTRAINT "shipments_ck_9" CHECK (shipment_status <> 'delivered' OR delivered_at IS NOT NULL),
    CONSTRAINT "shipments_ck_10" CHECK (shipment_status NOT IN ('planned','allocated','ready','cancelled') OR (handed_over_at IS NULL AND delivered_at IS NULL)),
    CONSTRAINT "shipments_ck_11" CHECK ((cancelled_at IS NOT NULL) = (shipment_status = 'cancelled')),
    CONSTRAINT "shipments_ck_12" CHECK (delivered_at IS NULL OR handed_over_at IS NOT NULL),
    CONSTRAINT "shipments_ck_13" CHECK (ready_at >= planned_at),
    CONSTRAINT "shipments_ck_14" CHECK (handed_over_at >= planned_at),
    CONSTRAINT "shipments_ck_15" CHECK (handed_over_at >= ready_at),
    CONSTRAINT "shipments_ck_16" CHECK (delivered_at >= handed_over_at),
    CONSTRAINT "shipments_ck_17" CHECK (cancelled_at >= planned_at),
    CONSTRAINT "shipments_ck_18" CHECK (fulfillment_type = 'ship' OR handed_over_at IS NULL OR (shipment_status = 'delivered' AND delivered_at = handed_over_at)),
    CONSTRAINT "shipments_ck_19" CHECK (shipment_id > 0),
    CONSTRAINT "shipments_ck_20" CHECK (row_version > 0),
    CONSTRAINT "shipments_ck_21" CHECK (updated_at >= created_at),
    CONSTRAINT "shipments_ck_22" CHECK ("shipment_number" IS NULL OR btrim("shipment_number") <> ''),
    CONSTRAINT "shipments_ck_23" CHECK ("shipment_number" = upper(btrim("shipment_number")) AND "shipment_number" !~ '[^ -~]'),
    CONSTRAINT "shipments_ck_24" CHECK ("fulfillment_type" IS NULL OR btrim("fulfillment_type") <> ''),
    CONSTRAINT "shipments_ck_25" CHECK ("fulfillment_type" IN ('carryout', 'pickup', 'ship')),
    CONSTRAINT "shipments_ck_26" CHECK ("shipping_address_role" IS NULL OR btrim("shipping_address_role") <> ''),
    CONSTRAINT "shipments_ck_27" CHECK ("shipping_address_role" IN ('shipping')),
    CONSTRAINT "shipments_ck_28" CHECK ("carrier" IS NULL OR btrim("carrier") <> ''),
    CONSTRAINT "shipments_ck_29" CHECK ("tracking_number" IS NULL OR btrim("tracking_number") <> ''),
    CONSTRAINT "shipments_ck_30" CHECK ("shipment_status" IS NULL OR btrim("shipment_status") <> ''),
    CONSTRAINT "shipments_ck_31" CHECK ("shipment_status" IN ('allocated', 'cancelled', 'delivered', 'handed_over', 'planned', 'ready')),
    CONSTRAINT "shipments_ck_32" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "shipments_ck_33" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "shipments_ix_0" ON "rmrg"."shipments" (order_id, planned_at);

CREATE INDEX "shipments_ix_1" ON "rmrg"."shipments" (origin_store_id, shipment_status);

CREATE INDEX "shipments_ix_2" ON "rmrg"."shipments" (origin_warehouse_id, shipment_status);

CREATE INDEX "shipments_ix_3" ON "rmrg"."shipments" (shipping_address_id, order_id, shipping_address_role);

CREATE INDEX "shipments_ix_4" ON "rmrg"."shipments" (shipment_status, planned_at);

CREATE UNIQUE INDEX "shipments_ix_5" ON "rmrg"."shipments" (carrier, tracking_number) WHERE carrier IS NOT NULL AND tracking_number IS NOT NULL;

CREATE TRIGGER "shipments_audit" BEFORE UPDATE ON rmrg."shipments" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('shipment_id');

CREATE TABLE "rmrg"."shipment_items" (
    "shipment_item_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "shipment_id" bigint NOT NULL,
    "order_id" bigint NOT NULL,
    "order_item_id" bigint NOT NULL,
    "quantity" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("shipment_id", "order_item_id"),
    UNIQUE ("shipment_item_id", "order_item_id", "order_id"),
    FOREIGN KEY ("shipment_id", "order_id") REFERENCES "rmrg"."shipments" ("shipment_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("order_item_id", "order_id") REFERENCES "rmrg"."order_items" ("order_item_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "shipment_items_ck_0" CHECK (quantity > 0),
    CONSTRAINT "shipment_items_ck_1" CHECK (shipment_item_id > 0),
    CONSTRAINT "shipment_items_ck_2" CHECK (row_version > 0),
    CONSTRAINT "shipment_items_ck_3" CHECK (updated_at >= created_at),
    CONSTRAINT "shipment_items_ck_4" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "shipment_items_ck_5" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "shipment_items_ix_0" ON "rmrg"."shipment_items" (shipment_id, order_id);

CREATE INDEX "shipment_items_ix_1" ON "rmrg"."shipment_items" (order_item_id, order_id);

CREATE INDEX "shipment_items_ix_2" ON "rmrg"."shipment_items" (order_id, shipment_item_id);

CREATE TRIGGER "shipment_items_audit" BEFORE UPDATE ON rmrg."shipment_items" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('shipment_item_id');

CREATE TABLE "rmrg"."returns" (
    "return_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "return_number" varchar(40) NOT NULL,
    "order_id" bigint NOT NULL,
    "return_status" varchar(20) DEFAULT 'requested' NOT NULL,
    "return_channel" varchar(15) NOT NULL,
    "receiving_store_id" bigint,
    "receiving_warehouse_id" bigint,
    "currency_code" char(3) NOT NULL,
    "merchandise_refund_amount" numeric(18,2) NOT NULL,
    "tax_refund_amount" numeric(18,2) NOT NULL,
    "shipping_refund_amount" numeric(18,2) NOT NULL,
    "shipping_tax_refund_amount" numeric(18,2) NOT NULL,
    "refund_total" numeric(18,2) NOT NULL,
    "requested_at" timestamp with time zone NOT NULL,
    "authorized_at" timestamp with time zone,
    "first_received_at" timestamp with time zone,
    "fully_received_at" timestamp with time zone,
    "resolved_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("return_number"),
    UNIQUE ("return_id", "order_id"),
    FOREIGN KEY ("order_id") REFERENCES "rmrg"."orders" ("order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("receiving_store_id") REFERENCES "rmrg"."stores" ("store_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("receiving_warehouse_id") REFERENCES "rmrg"."warehouses" ("warehouse_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "returns_ck_0" CHECK ((receiving_store_id IS NULL) <> (receiving_warehouse_id IS NULL)),
    CONSTRAINT "returns_ck_1" CHECK (return_channel <> 'store' OR receiving_store_id IS NOT NULL),
    CONSTRAINT "returns_ck_2" CHECK (refund_total = merchandise_refund_amount + tax_refund_amount + shipping_refund_amount + shipping_tax_refund_amount),
    CONSTRAINT "returns_ck_3" CHECK (return_status NOT IN ('authorized','partially_received','received','closed') OR authorized_at IS NOT NULL),
    CONSTRAINT "returns_ck_4" CHECK (return_status NOT IN ('partially_received','received','closed') OR first_received_at IS NOT NULL),
    CONSTRAINT "returns_ck_5" CHECK (return_status NOT IN ('received','closed') OR fully_received_at IS NOT NULL),
    CONSTRAINT "returns_ck_6" CHECK (return_status NOT IN ('requested','rejected','cancelled') OR (first_received_at IS NULL AND fully_received_at IS NULL)),
    CONSTRAINT "returns_ck_7" CHECK (return_status <> 'rejected' OR authorized_at IS NULL),
    CONSTRAINT "returns_ck_8" CHECK ((resolved_at IS NOT NULL) = (return_status IN ('rejected','cancelled','closed'))),
    CONSTRAINT "returns_ck_9" CHECK (authorized_at >= requested_at),
    CONSTRAINT "returns_ck_10" CHECK (first_received_at >= requested_at),
    CONSTRAINT "returns_ck_11" CHECK (fully_received_at >= requested_at),
    CONSTRAINT "returns_ck_12" CHECK (resolved_at >= requested_at),
    CONSTRAINT "returns_ck_13" CHECK (first_received_at >= authorized_at),
    CONSTRAINT "returns_ck_14" CHECK (fully_received_at >= authorized_at),
    CONSTRAINT "returns_ck_15" CHECK (resolved_at >= authorized_at),
    CONSTRAINT "returns_ck_16" CHECK (fully_received_at >= first_received_at),
    CONSTRAINT "returns_ck_17" CHECK (resolved_at >= first_received_at),
    CONSTRAINT "returns_ck_18" CHECK (resolved_at >= fully_received_at),
    CONSTRAINT "returns_ck_19" CHECK (return_id > 0),
    CONSTRAINT "returns_ck_20" CHECK (row_version > 0),
    CONSTRAINT "returns_ck_21" CHECK (updated_at >= created_at),
    CONSTRAINT "returns_ck_22" CHECK ("return_number" IS NULL OR btrim("return_number") <> ''),
    CONSTRAINT "returns_ck_23" CHECK ("return_number" = upper(btrim("return_number")) AND "return_number" !~ '[^ -~]'),
    CONSTRAINT "returns_ck_24" CHECK ("return_status" IS NULL OR btrim("return_status") <> ''),
    CONSTRAINT "returns_ck_25" CHECK ("return_status" IN ('authorized', 'cancelled', 'closed', 'partially_received', 'received', 'rejected', 'requested')),
    CONSTRAINT "returns_ck_26" CHECK ("return_channel" IS NULL OR btrim("return_channel") <> ''),
    CONSTRAINT "returns_ck_27" CHECK ("return_channel" IN ('mail', 'store')),
    CONSTRAINT "returns_ck_28" CHECK ("currency_code" IS NULL OR btrim("currency_code") <> ''),
    CONSTRAINT "returns_ck_29" CHECK (currency_code IN ('CAD','USD')),
    CONSTRAINT "returns_ck_30" CHECK ("merchandise_refund_amount" >= 0),
    CONSTRAINT "returns_ck_31" CHECK ("tax_refund_amount" >= 0),
    CONSTRAINT "returns_ck_32" CHECK ("shipping_refund_amount" >= 0),
    CONSTRAINT "returns_ck_33" CHECK ("shipping_tax_refund_amount" >= 0),
    CONSTRAINT "returns_ck_34" CHECK ("refund_total" >= 0),
    CONSTRAINT "returns_ck_35" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "returns_ck_36" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "returns_ix_0" ON "rmrg"."returns" (order_id, requested_at);

CREATE INDEX "returns_ix_1" ON "rmrg"."returns" (receiving_store_id, return_status);

CREATE INDEX "returns_ix_2" ON "rmrg"."returns" (receiving_warehouse_id, return_status);

CREATE INDEX "returns_ix_3" ON "rmrg"."returns" (return_status, requested_at);

CREATE TRIGGER "returns_audit" BEFORE UPDATE ON rmrg."returns" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('return_id');

CREATE TABLE "rmrg"."return_items" (
    "return_item_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "return_id" bigint NOT NULL,
    "order_id" bigint NOT NULL,
    "order_item_id" bigint NOT NULL,
    "shipment_item_id" bigint NOT NULL,
    "quantity_requested" integer NOT NULL,
    "quantity_authorized" integer NOT NULL,
    "quantity_received" integer NOT NULL,
    "quantity_restocked" integer NOT NULL,
    "quantity_disposed" integer NOT NULL,
    "reason_code" varchar(25) NOT NULL,
    "disposition" varchar(20) NOT NULL,
    "merchandise_refund_amount" numeric(18,2) NOT NULL,
    "tax_refund_amount" numeric(18,2) NOT NULL,
    "last_received_at" timestamp with time zone,
    "inspected_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("return_id", "shipment_item_id"),
    UNIQUE ("return_item_id", "return_id", "order_item_id", "order_id"),
    FOREIGN KEY ("return_id", "order_id") REFERENCES "rmrg"."returns" ("return_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("order_item_id", "order_id") REFERENCES "rmrg"."order_items" ("order_item_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("shipment_item_id", "order_item_id", "order_id") REFERENCES "rmrg"."shipment_items" ("shipment_item_id", "order_item_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "return_items_ck_0" CHECK (quantity_requested > 0),
    CONSTRAINT "return_items_ck_1" CHECK (quantity_authorized BETWEEN 0 AND quantity_requested),
    CONSTRAINT "return_items_ck_2" CHECK (quantity_received BETWEEN 0 AND quantity_authorized),
    CONSTRAINT "return_items_ck_3" CHECK (quantity_restocked >= 0),
    CONSTRAINT "return_items_ck_4" CHECK (quantity_disposed >= 0),
    CONSTRAINT "return_items_ck_5" CHECK (quantity_restocked::bigint + quantity_disposed::bigint <= quantity_received),
    CONSTRAINT "return_items_ck_6" CHECK ((last_received_at IS NOT NULL) = (quantity_received > 0)),
    CONSTRAINT "return_items_ck_7" CHECK ((inspected_at IS NULL) = (disposition = 'pending')),
    CONSTRAINT "return_items_ck_8" CHECK (inspected_at >= last_received_at),
    CONSTRAINT "return_items_ck_9" CHECK (disposition = 'pending' OR (quantity_received > 0 AND quantity_restocked::bigint + quantity_disposed::bigint = quantity_received)),
    CONSTRAINT "return_items_ck_10" CHECK (disposition <> 'restock' OR quantity_disposed = 0),
    CONSTRAINT "return_items_ck_11" CHECK (disposition <> 'dispose' OR quantity_restocked = 0),
    CONSTRAINT "return_items_ck_12" CHECK (disposition <> 'mixed' OR (quantity_restocked > 0 AND quantity_disposed > 0)),
    CONSTRAINT "return_items_ck_13" CHECK (quantity_authorized <> 0 OR (merchandise_refund_amount = 0 AND tax_refund_amount = 0)),
    CONSTRAINT "return_items_ck_14" CHECK (return_item_id > 0),
    CONSTRAINT "return_items_ck_15" CHECK (row_version > 0),
    CONSTRAINT "return_items_ck_16" CHECK (updated_at >= created_at),
    CONSTRAINT "return_items_ck_17" CHECK ("reason_code" IS NULL OR btrim("reason_code") <> ''),
    CONSTRAINT "return_items_ck_18" CHECK ("reason_code" IN ('changed_mind', 'damaged', 'defective', 'other', 'wrong_item', 'wrong_size')),
    CONSTRAINT "return_items_ck_19" CHECK ("disposition" IS NULL OR btrim("disposition") <> ''),
    CONSTRAINT "return_items_ck_20" CHECK ("disposition" IN ('dispose', 'mixed', 'pending', 'restock')),
    CONSTRAINT "return_items_ck_21" CHECK ("merchandise_refund_amount" >= 0),
    CONSTRAINT "return_items_ck_22" CHECK ("tax_refund_amount" >= 0),
    CONSTRAINT "return_items_ck_23" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "return_items_ck_24" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "return_items_ix_0" ON "rmrg"."return_items" (return_id, order_id);

CREATE INDEX "return_items_ix_1" ON "rmrg"."return_items" (order_item_id, order_id);

CREATE INDEX "return_items_ix_2" ON "rmrg"."return_items" (shipment_item_id, order_item_id, order_id);

CREATE INDEX "return_items_ix_3" ON "rmrg"."return_items" (order_id, return_item_id);

CREATE TRIGGER "return_items_audit" BEFORE UPDATE ON rmrg."return_items" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('return_item_id');

CREATE TABLE "rmrg"."payments" (
    "payment_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "order_id" bigint NOT NULL,
    "payment_request_key" varchar(100) NOT NULL,
    "parent_payment_id" bigint,
    "return_id" bigint,
    "operation_type" varchar(15) NOT NULL,
    "payment_method" varchar(20) NOT NULL,
    "provider" varchar(50) NOT NULL,
    "provider_transaction_id" varchar(100),
    "payment_status" varchar(15) DEFAULT 'pending' NOT NULL,
    "amount" numeric(18,2) NOT NULL,
    "currency_code" char(3) NOT NULL,
    "failure_code" varchar(50),
    "attempted_at" timestamp with time zone NOT NULL,
    "processed_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("payment_request_key"),
    UNIQUE ("payment_id", "order_id"),
    FOREIGN KEY ("order_id") REFERENCES "rmrg"."orders" ("order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("parent_payment_id", "order_id") REFERENCES "rmrg"."payments" ("payment_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("return_id", "order_id") REFERENCES "rmrg"."returns" ("return_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "payments_ck_0" CHECK (amount > 0),
    CONSTRAINT "payments_ck_1" CHECK (parent_payment_id <> payment_id),
    CONSTRAINT "payments_ck_2" CHECK (operation_type NOT IN ('refund','void') OR parent_payment_id IS NOT NULL),
    CONSTRAINT "payments_ck_3" CHECK (operation_type <> 'authorization' OR parent_payment_id IS NULL),
    CONSTRAINT "payments_ck_4" CHECK (return_id IS NULL OR operation_type = 'refund'),
    CONSTRAINT "payments_ck_5" CHECK (payment_method <> 'cash' OR operation_type IN ('capture','refund')),
    CONSTRAINT "payments_ck_6" CHECK (payment_status <> 'succeeded' OR payment_method = 'cash' OR provider_transaction_id IS NOT NULL),
    CONSTRAINT "payments_ck_7" CHECK ((failure_code IS NOT NULL) = (payment_status = 'failed')),
    CONSTRAINT "payments_ck_8" CHECK ((processed_at IS NULL) = (payment_status = 'pending')),
    CONSTRAINT "payments_ck_9" CHECK (processed_at >= attempted_at),
    CONSTRAINT "payments_ck_10" CHECK (payment_id > 0),
    CONSTRAINT "payments_ck_11" CHECK (row_version > 0),
    CONSTRAINT "payments_ck_12" CHECK (updated_at >= created_at),
    CONSTRAINT "payments_ck_13" CHECK ("payment_request_key" IS NULL OR btrim("payment_request_key") <> ''),
    CONSTRAINT "payments_ck_14" CHECK ("operation_type" IS NULL OR btrim("operation_type") <> ''),
    CONSTRAINT "payments_ck_15" CHECK ("operation_type" IN ('authorization', 'capture', 'refund', 'void')),
    CONSTRAINT "payments_ck_16" CHECK ("payment_method" IS NULL OR btrim("payment_method") <> ''),
    CONSTRAINT "payments_ck_17" CHECK ("payment_method" IN ('card', 'cash', 'gift_card', 'wallet')),
    CONSTRAINT "payments_ck_18" CHECK ("provider" IS NULL OR btrim("provider") <> ''),
    CONSTRAINT "payments_ck_19" CHECK ("provider_transaction_id" IS NULL OR btrim("provider_transaction_id") <> ''),
    CONSTRAINT "payments_ck_20" CHECK ("payment_status" IS NULL OR btrim("payment_status") <> ''),
    CONSTRAINT "payments_ck_21" CHECK ("payment_status" IN ('failed', 'pending', 'succeeded')),
    CONSTRAINT "payments_ck_22" CHECK ("amount" >= 0),
    CONSTRAINT "payments_ck_23" CHECK ("currency_code" IS NULL OR btrim("currency_code") <> ''),
    CONSTRAINT "payments_ck_24" CHECK (currency_code IN ('CAD','USD')),
    CONSTRAINT "payments_ck_25" CHECK ("failure_code" IS NULL OR btrim("failure_code") <> ''),
    CONSTRAINT "payments_ck_26" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "payments_ck_27" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "payments_ix_0" ON "rmrg"."payments" (order_id, attempted_at, payment_id);

CREATE INDEX "payments_ix_1" ON "rmrg"."payments" (parent_payment_id, order_id);

CREATE INDEX "payments_ix_2" ON "rmrg"."payments" (return_id, order_id);

CREATE INDEX "payments_ix_3" ON "rmrg"."payments" (attempted_at) WHERE payment_status = 'pending';

CREATE UNIQUE INDEX "payments_ix_4" ON "rmrg"."payments" (provider, provider_transaction_id, operation_type) WHERE provider_transaction_id IS NOT NULL;

CREATE TRIGGER "payments_audit" BEFORE UPDATE ON rmrg."payments" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('payment_id');

CREATE TABLE "rmrg"."payment_allocations" (
    "payment_allocation_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "payment_id" bigint NOT NULL,
    "order_id" bigint NOT NULL,
    "order_item_id" bigint,
    "return_item_id" bigint,
    "return_id" bigint,
    "allocation_type" varchar(20) NOT NULL,
    "amount" numeric(18,2) NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    FOREIGN KEY ("payment_id", "order_id") REFERENCES "rmrg"."payments" ("payment_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("order_item_id", "order_id") REFERENCES "rmrg"."order_items" ("order_item_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("return_item_id", "return_id", "order_item_id", "order_id") REFERENCES "rmrg"."return_items" ("return_item_id", "return_id", "order_item_id", "order_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "payment_allocations_ck_0" CHECK (amount > 0),
    CONSTRAINT "payment_allocations_ck_1" CHECK ((order_item_id IS NOT NULL) = (allocation_type IN ('merchandise','tax'))),
    CONSTRAINT "payment_allocations_ck_2" CHECK ((return_id IS NULL) = (return_item_id IS NULL)),
    CONSTRAINT "payment_allocations_ck_3" CHECK (return_item_id IS NULL OR order_item_id IS NOT NULL),
    CONSTRAINT "payment_allocations_ck_4" CHECK (payment_allocation_id > 0),
    CONSTRAINT "payment_allocations_ck_5" CHECK (row_version > 0),
    CONSTRAINT "payment_allocations_ck_6" CHECK (updated_at >= created_at),
    CONSTRAINT "payment_allocations_ck_7" CHECK ("allocation_type" IS NULL OR btrim("allocation_type") <> ''),
    CONSTRAINT "payment_allocations_ck_8" CHECK ("allocation_type" IN ('merchandise', 'shipping', 'shipping_tax', 'tax')),
    CONSTRAINT "payment_allocations_ck_9" CHECK ("amount" >= 0),
    CONSTRAINT "payment_allocations_ck_10" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "payment_allocations_ck_11" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE UNIQUE INDEX "payment_allocations_ix_0" ON "rmrg"."payment_allocations" (payment_id, order_item_id, allocation_type) WHERE order_item_id IS NOT NULL AND return_item_id IS NULL;

CREATE UNIQUE INDEX "payment_allocations_ix_1" ON "rmrg"."payment_allocations" (payment_id, return_item_id, allocation_type) WHERE return_item_id IS NOT NULL;

CREATE UNIQUE INDEX "payment_allocations_ix_2" ON "rmrg"."payment_allocations" (payment_id, allocation_type) WHERE order_item_id IS NULL;

CREATE INDEX "payment_allocations_ix_3" ON "rmrg"."payment_allocations" (payment_id, order_id);

CREATE INDEX "payment_allocations_ix_4" ON "rmrg"."payment_allocations" (order_item_id, order_id);

CREATE INDEX "payment_allocations_ix_5" ON "rmrg"."payment_allocations" (return_item_id, return_id, order_item_id, order_id);

CREATE INDEX "payment_allocations_ix_6" ON "rmrg"."payment_allocations" (order_id, payment_allocation_id);

CREATE TRIGGER "payment_allocations_audit" BEFORE UPDATE ON rmrg."payment_allocations" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('payment_allocation_id');

CREATE TABLE "rmrg"."stock_movements" (
    "stock_movement_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "inventory_id" bigint NOT NULL,
    "movement_key" varchar(100) NOT NULL,
    "movement_type" varchar(25) NOT NULL,
    "quantity_delta" integer NOT NULL,
    "reserved_delta" integer NOT NULL,
    "unavailable_delta" integer NOT NULL,
    "occurred_at" timestamp with time zone NOT NULL,
    "reason_code" varchar(30) NOT NULL,
    "reference_number" varchar(100),
    "source_document_type" varchar(25),
    "transfer_id" uuid,
    "shipment_item_id" bigint,
    "return_item_id" bigint,
    "reverses_movement_id" bigint,
    "notes" varchar(500),
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "row_version" bigint DEFAULT 1 NOT NULL,
    "created_by" varchar(100) NOT NULL,
    "updated_by" varchar(100) NOT NULL,
    UNIQUE ("movement_key"),
    FOREIGN KEY ("inventory_id") REFERENCES "rmrg"."inventory" ("inventory_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("shipment_item_id") REFERENCES "rmrg"."shipment_items" ("shipment_item_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("return_item_id") REFERENCES "rmrg"."return_items" ("return_item_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("reverses_movement_id") REFERENCES "rmrg"."stock_movements" ("stock_movement_id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT "stock_movements_ck_0" CHECK (quantity_delta <> 0 OR reserved_delta <> 0 OR unavailable_delta <> 0),
    CONSTRAINT "stock_movements_ck_1" CHECK ((transfer_id IS NOT NULL) = (movement_type IN ('transfer_in','transfer_out'))),
    CONSTRAINT "stock_movements_ck_2" CHECK ((reverses_movement_id IS NOT NULL) = (movement_type = 'reversal')),
    CONSTRAINT "stock_movements_ck_3" CHECK (reverses_movement_id <> stock_movement_id),
    CONSTRAINT "stock_movements_ck_4" CHECK (shipment_item_id IS NULL OR return_item_id IS NULL),
    CONSTRAINT "stock_movements_ck_5" CHECK (movement_type <> 'sale' OR shipment_item_id IS NOT NULL),
    CONSTRAINT "stock_movements_ck_6" CHECK (movement_type <> 'return' OR return_item_id IS NOT NULL),
    CONSTRAINT "stock_movements_ck_7" CHECK ((source_document_type IS NULL) = (reference_number IS NULL)),
    CONSTRAINT "stock_movements_ck_8" CHECK (movement_type NOT IN ('opening','receipt','return','transfer_in') OR (quantity_delta > 0 AND reserved_delta = 0 AND unavailable_delta = 0)),
    CONSTRAINT "stock_movements_ck_9" CHECK (movement_type <> 'transfer_out' OR (quantity_delta < 0 AND reserved_delta = 0 AND unavailable_delta = 0)),
    CONSTRAINT "stock_movements_ck_10" CHECK (movement_type <> 'sale' OR (quantity_delta < 0 AND reserved_delta BETWEEN quantity_delta AND 0 AND unavailable_delta = 0)),
    CONSTRAINT "stock_movements_ck_11" CHECK (movement_type NOT IN ('reserve','release') OR (quantity_delta = 0 AND unavailable_delta = 0 AND ((movement_type = 'reserve' AND reserved_delta > 0) OR (movement_type = 'release' AND reserved_delta < 0)))),
    CONSTRAINT "stock_movements_ck_12" CHECK (movement_type NOT IN ('quarantine','unquarantine') OR (quantity_delta = 0 AND reserved_delta = 0 AND ((movement_type = 'quarantine' AND unavailable_delta > 0) OR (movement_type = 'unquarantine' AND unavailable_delta < 0)))),
    CONSTRAINT "stock_movements_ck_13" CHECK (movement_type <> 'adjustment' OR (quantity_delta <> 0 AND reserved_delta = 0 AND unavailable_delta = 0)),
    CONSTRAINT "stock_movements_ck_14" CHECK (stock_movement_id > 0),
    CONSTRAINT "stock_movements_ck_15" CHECK (row_version > 0),
    CONSTRAINT "stock_movements_ck_16" CHECK (updated_at >= created_at),
    CONSTRAINT "stock_movements_ck_17" CHECK ("movement_key" IS NULL OR btrim("movement_key") <> ''),
    CONSTRAINT "stock_movements_ck_18" CHECK ("movement_type" IS NULL OR btrim("movement_type") <> ''),
    CONSTRAINT "stock_movements_ck_19" CHECK ("movement_type" IN ('adjustment', 'opening', 'quarantine', 'receipt', 'release', 'reserve', 'return', 'reversal', 'sale', 'transfer_in', 'transfer_out', 'unquarantine')),
    CONSTRAINT "stock_movements_ck_20" CHECK ("reason_code" IS NULL OR btrim("reason_code") <> ''),
    CONSTRAINT "stock_movements_ck_21" CHECK ("reason_code" IN ('allocation', 'allocation_release', 'correction', 'customer_return', 'cycle_count', 'damage', 'fulfillment', 'initial_load', 'location_transfer', 'purchase_receipt', 'quality_release')),
    CONSTRAINT "stock_movements_ck_22" CHECK ("reference_number" IS NULL OR btrim("reference_number") <> ''),
    CONSTRAINT "stock_movements_ck_23" CHECK ("source_document_type" IS NULL OR btrim("source_document_type") <> ''),
    CONSTRAINT "stock_movements_ck_24" CHECK ("source_document_type" IN ('adjustment', 'cycle_count', 'damage_report', 'purchase_receipt')),
    CONSTRAINT "stock_movements_ck_25" CHECK ("notes" IS NULL OR btrim("notes") <> ''),
    CONSTRAINT "stock_movements_ck_26" CHECK ("created_by" IS NULL OR btrim("created_by") <> ''),
    CONSTRAINT "stock_movements_ck_27" CHECK ("updated_by" IS NULL OR btrim("updated_by") <> '')
);

CREATE INDEX "stock_movements_ix_0" ON "rmrg"."stock_movements" (inventory_id, occurred_at, stock_movement_id);

CREATE INDEX "stock_movements_ix_1" ON "rmrg"."stock_movements" (shipment_item_id) WHERE shipment_item_id IS NOT NULL;

CREATE INDEX "stock_movements_ix_2" ON "rmrg"."stock_movements" (return_item_id) WHERE return_item_id IS NOT NULL;

CREATE UNIQUE INDEX "stock_movements_ix_3" ON "rmrg"."stock_movements" (transfer_id, movement_type) WHERE transfer_id IS NOT NULL;

CREATE UNIQUE INDEX "stock_movements_ix_4" ON "rmrg"."stock_movements" (reverses_movement_id) WHERE reverses_movement_id IS NOT NULL;

CREATE TRIGGER "stock_movements_audit" BEFORE UPDATE ON rmrg."stock_movements" FOR EACH ROW EXECUTE FUNCTION rmrg.maintain_audit('stock_movement_id');
